apiVersion: v1
kind: ConfigMap
metadata:
  name: cicero-n8n-config
  namespace: cicero
data:
  N8N_PORT: "3008"
  N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
  N8N_SECURE_COOKIE: "true"
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_HOST: "cicero-db-rw.cicero.svc.cluster.local"
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_DATABASE: "app"
