apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: julius-ingress
  namespace: julius
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - julius.staging.mercury.local
      secretName: julius-tls
  rules:
    - host: julius.staging.mercury.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: julius-n8n
                port:
                  number: 3008
