apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: brutus
resources:
  - namespace.yaml
  - secrets.yaml
  - database.yaml
  - scheduled-backup.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - certificate.yaml
